# Puts the fixed Funny Valentine files into your CSDK12 addon:
#  - the fixed materials (always), clearing stale compiled ones
#  - funny_valentine.dmx, if one sits next to this script (fixed model mesh)
# Usage: double-click "Fix FV materials.bat" (or drag your CSDK12 folder onto it).
#        Run it with -Check after "Compile All Assets" to confirm the texture compiled.
param([string]$CsdkPath = "", [switch]$Check)
$ErrorActionPreference = "Stop"
function Say($m, $c = "Gray") { Write-Host $m -ForegroundColor $c }

$Body = @'
// Funny Valentine - generated by fv_build.py
// Deadlock's pbr.vfx only reads the layer-1 inputs (TextureColor1, TextureNormal1, ...);
// un-suffixed names like "TextureColor" are silently ignored. Layout matches Valve's hero materials.
"Layer0"
{
	"shader"	"pbr.vfx"
	"F_RENDER_BACKFACES"	"1"
	"F_SOLID_COLOR_OUTLINE"	"1"
	"F_USE_NPR_LIGHTING"	"1"
	"F_USE_STATUS_EFFECTS_PROXY"	"1"
	"g_bMaskColorTint1"	"1"
	"g_bMaskVertexColorTint1"	"1"
	"g_flAlbedoScrollQuantize1"	"0"
	"g_flHighlightAOStrength1"	"1"
	"g_flHighlightCoverage1"	"0"
	"g_flHighlightHardness1"	"0"
	"g_flHighlightNormalStrength1"	"64"
	"g_flHighlightRadius1"	"256"
	"g_flHighlightTintBrightness1"	"1"
	"g_flInvertHighlight1"	"0"
	"g_flNormalAndRoughnessScrollQuantize1"	"0"
	"g_fSolidOutlineVertexColorTint"	"0"
	"g_fVertexColorStrength1"	"1"
	"g_vAlbedoContrastSaturationBrightness1"	"[1.000000 1.000000 1.000000 0.000000]"
	"g_vAlbedoScrollSpeed1"	"[0.000000 0.000000 0.000000 0.000000]"
	"g_vColorTint1"	"[1.000000 1.000000 1.000000 0.000000]"
	"g_vHighlightPositionWs1"	"[0.000000 0.000000 72.000000 0.000000]"
	"g_vHighlightTint1"	"[1.000000 1.000000 1.000000 0.000000]"
	"g_vNormalAndRoughnessScrollSpeed1"	"[0.000000 0.000000 0.000000 0.000000]"
	"g_vSolidOutlineAdditive"	"[0.011765 0.011765 0.011765 0.000000]"
	"g_vSolidOutlineTint"	"[0.101961 0.101961 0.101961 0.000000]"
	"TextureColor1"	"materials/funny_valentine/fv_body_color.png"
	"TextureAmbientOcclusion1"	"[1.000000 1.000000 1.000000 0.000000]"
	"TextureMetalness1"	"[0.000000 0.000000 0.000000 0.000000]"
	"TextureNormal1"	"[0.501961 0.501961 1.000000 0.000000]"
	"TextureRoughness1"	"[0.400000 0.400000 0.400000 0.000000]"
	"TextureSelfIllumMask1"	"[0.000000 0.000000 0.000000 0.000000]"
	"TextureNprOutlineMask1"	"[1.000000 1.000000 1.000000 0.000000]"
	"TextureNprTramsissiveColor1"	"[0.000000 0.000000 0.000000 0.000000]"
	"TextureRimLightMask1"	"[1.000000 1.000000 1.000000 0.000000]"
	"TextureTintMask1"	"[1.000000 1.000000 1.000000 0.000000]"
}

'@
$Eyes = @'
// Funny Valentine - generated by fv_build.py
// Deadlock's pbr.vfx only reads the layer-1 inputs (TextureColor1, TextureNormal1, ...);
// un-suffixed names like "TextureColor" are silently ignored. Layout matches Valve's hero materials.
"Layer0"
{
	"shader"	"pbr.vfx"
	"F_RENDER_BACKFACES"	"1"
	"F_SOLID_COLOR_OUTLINE"	"1"
	"F_USE_NPR_LIGHTING"	"1"
	"F_USE_STATUS_EFFECTS_PROXY"	"1"
	"g_bMaskColorTint1"	"1"
	"g_bMaskVertexColorTint1"	"1"
	"g_flAlbedoScrollQuantize1"	"0"
	"g_flHighlightAOStrength1"	"1"
	"g_flHighlightCoverage1"	"0"
	"g_flHighlightHardness1"	"0"
	"g_flHighlightNormalStrength1"	"64"
	"g_flHighlightRadius1"	"256"
	"g_flHighlightTintBrightness1"	"1"
	"g_flInvertHighlight1"	"0"
	"g_flNormalAndRoughnessScrollQuantize1"	"0"
	"g_fSolidOutlineVertexColorTint"	"0"
	"g_fVertexColorStrength1"	"1"
	"g_vAlbedoContrastSaturationBrightness1"	"[1.000000 1.000000 1.000000 0.000000]"
	"g_vAlbedoScrollSpeed1"	"[0.000000 0.000000 0.000000 0.000000]"
	"g_vColorTint1"	"[1.000000 1.000000 1.000000 0.000000]"
	"g_vHighlightPositionWs1"	"[0.000000 0.000000 72.000000 0.000000]"
	"g_vHighlightTint1"	"[1.000000 1.000000 1.000000 0.000000]"
	"g_vNormalAndRoughnessScrollSpeed1"	"[0.000000 0.000000 0.000000 0.000000]"
	"g_vSolidOutlineAdditive"	"[0.011765 0.011765 0.011765 0.000000]"
	"g_vSolidOutlineTint"	"[0.101961 0.101961 0.101961 0.000000]"
	"TextureColor1"	"materials/funny_valentine/fv_eyes_color.png"
	"TextureAmbientOcclusion1"	"[1.000000 1.000000 1.000000 0.000000]"
	"TextureMetalness1"	"[0.000000 0.000000 0.000000 0.000000]"
	"TextureNormal1"	"[0.501961 0.501961 1.000000 0.000000]"
	"TextureRoughness1"	"[0.400000 0.400000 0.400000 0.000000]"
	"TextureSelfIllumMask1"	"[0.000000 0.000000 0.000000 0.000000]"
	"TextureNprOutlineMask1"	"[1.000000 1.000000 1.000000 0.000000]"
	"TextureNprTramsissiveColor1"	"[0.000000 0.000000 0.000000 0.000000]"
	"TextureRimLightMask1"	"[1.000000 1.000000 1.000000 0.000000]"
	"TextureTintMask1"	"[1.000000 1.000000 1.000000 0.000000]"
}

'@

function Find-Addon {
    $tail = "funny_valentine\models\heroes_wip\doorman_v2\doorman.vmdl"
    $home_ = if ($env:USERPROFILE) { $env:USERPROFILE } else { $HOME }
    # (folder, how deep to look) - specific spots first, whole drives last
    $places = @()
    if ($CsdkPath) { $places += ,@($CsdkPath, 3) }
    foreach ($p in "C:\CSDK12", "D:\CSDK12", "C:\Reduced_CSDK_12", "D:\Reduced_CSDK_12") { $places += ,@($p, 2) }
    foreach ($f in "Desktop", "Downloads", "Documents", "OneDrive") { $places += ,@((Join-Path $home_ $f), 4) }
    $skip = '^(Windows|Program Files|Program Files \(x86\)|ProgramData|\$Recycle\.Bin|System Volume Information|Users|Recovery|PerfLogs)$'
    foreach ($d in [System.IO.DriveInfo]::GetDrives() | Where-Object { $_.DriveType -eq "Fixed" }) {
        foreach ($top in Get-ChildItem -LiteralPath $d.RootDirectory.FullName -Directory -ErrorAction SilentlyContinue) {
            if ($top.Name -notmatch $skip) { $places += ,@($top.FullName, 3) }
        }
    }
    foreach ($pl in $places) {
        $root, $depth = $pl
        if (-not $root -or -not (Test-Path -LiteralPath $root)) { continue }
        foreach ($c in (Join-Path $root "content\citadel_addons"), (Join-Path $root "citadel_addons")) {
            if (Test-Path -LiteralPath (Join-Path $c $tail)) { return (Join-Path $c "funny_valentine") }
        }
        $hit = Get-ChildItem -LiteralPath $root -Directory -Recurse -Depth $depth -Filter "citadel_addons" -ErrorAction SilentlyContinue |
            Where-Object { Test-Path -LiteralPath (Join-Path $_.FullName $tail) } | Select-Object -First 1
        if ($hit) { return (Join-Path $hit.FullName "funny_valentine") }
    }
    try {
        Add-Type -AssemblyName System.Windows.Forms
        $dlg = New-Object System.Windows.Forms.FolderBrowserDialog
        $dlg.Description = "Pick your CSDK12 folder (the one with 'content' and 'game' inside)"
        if ($dlg.ShowDialog() -eq "OK") {
            $p = Join-Path $dlg.SelectedPath "content\citadel_addons\funny_valentine"
            if (Test-Path -LiteralPath $p) { return $p }
        }
    } catch { }
    throw "Couldn't find CSDK12\content\citadel_addons\funny_valentine. Drag your CSDK12 folder onto the .bat file."
}

try {
    $addon = Find-Addon
    $contentAddons = Split-Path $addon
    $csdk = Split-Path (Split-Path $contentAddons)
    $gameMats = Join-Path $csdk "game\citadel_addons\funny_valentine\materials\funny_valentine"
    $mats = Join-Path $addon "materials\funny_valentine"
    Say "Addon: $addon"

    if ($Check) {
        $tex = Get-ChildItem -LiteralPath $gameMats -Filter "fv_body_color*.vtex_c" -ErrorAction SilentlyContinue | Sort-Object Length -Descending | Select-Object -First 1
        if ($tex -and $tex.Length -gt 500KB) {
            Say ("OK - his texture compiled ({0} MB). Now click compile + make vpk in the VMDL Compiler; the vpk should be 3-4 MB." -f [math]::Round($tex.Length / 1MB, 1)) "Green"
        } else {
            Say "Not compiled yet: no fv_body_color texture in $gameMats" "Red"
            Say "Run 'Compile All Assets' on funny_valentine in CSDK12, then run this check again." "Yellow"
        }
        return
    }

    foreach ($png in "fv_body_color.png", "fv_eyes_color.png") {
        if (-not (Test-Path -LiteralPath (Join-Path $mats $png))) { throw "$png is missing from $mats - re-unzip funny_valentine_addon.zip into $contentAddons first." }
    }
    $bodyPath = Join-Path $mats "fv_body.vmat"
    $sameVmats = (Test-Path -LiteralPath $bodyPath) -and ([System.IO.File]::ReadAllText($bodyPath) -eq $Body)
    [System.IO.File]::WriteAllText($bodyPath, $Body)
    [System.IO.File]::WriteAllText((Join-Path $mats "fv_eyes.vmat"), $Eyes)
    Say "  materials: fixed fv_body.vmat + fv_eyes.vmat in place" "Green"

    # keep the compiled materials if they're already the good ones (real colour texture present)
    $goodTex = Get-ChildItem -LiteralPath $gameMats -Filter "fv_body_color*.vtex_c" -ErrorAction SilentlyContinue | Where-Object { $_.Length -gt 500KB }
    $needCompileAll = $true
    if ($sameVmats -and $goodTex) {
        $needCompileAll = $false
        Say "  compiled materials are already good - keeping them" "Green"
    } else {
        $old = Join-Path $csdk "game\citadel_addons\funny_valentine\materials"
        if (Test-Path -LiteralPath $old) { Remove-Item -LiteralPath $old -Recurse -Force; Say "  deleted old compiled materials" "Green" }
    }

    # fixed model mesh shipped next to this script
    $dmx = Join-Path $PSScriptRoot "funny_valentine.dmx"
    if (Test-Path -LiteralPath $dmx) {
        $dest = Join-Path $addon "models\heroes_wip\doorman_v2\funny_valentine.dmx"
        Copy-Item -LiteralPath $dmx -Destination $dest -Force
        # brand-new timestamp, otherwise the compiler keeps its older synced copy
        (Get-Item -LiteralPath $dest).LastWriteTime = Get-Date
        Say "  model: new funny_valentine.dmx in place" "Green"
    }

    foreach ($stray in (Join-Path $contentAddons "fv_material_fix"), (Join-Path $addon "funny_valentine")) {
        if (Test-Path -LiteralPath $stray) { Remove-Item -LiteralPath $stray -Recurse -Force; Say "  removed stray folder $stray" }
    }
    Say ""
    Say "Next:" "Cyan"
    if ($needCompileAll) {
        Say "  1. CSDK12: right-click funny_valentine > Compile All Assets"
        Say "  2. Run 'Check FV materials.bat' - it should say OK"
        Say "  3. VMDL Compiler: compile, then Yes to make the vpk (should be 3-4 MB)"
    } else {
        Say "  1. VMDL Compiler: compile, then Yes to make the vpk (should be 3-4 MB)"
        Say "  (no need to run Compile All Assets again)"
    }
} catch {
    Say ""
    Say "Failed: $($_.Exception.Message)" "Red"
    exit 1
}
